version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - ldap
    environment:
      - DJANGO_SETTINGS_MODULE=brayanproject.settings

  ldap:
    image: osixia/openldap:1.5.0
    environment:
      - LDAP_ORGANISATION=Example Organization
      - LDAP_DOMAIN=example.com
      - LDAP_ADMIN_PASSWORD=admin123
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - ldap-data:/var/lib/ldap
      - ldap-config:/etc/ldap/slapd.d

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap
      - PHPLDAPADMIN_HTTPS=false
      - PHPLDAPADMIN_TRUST_PROXY_SSL=true
      - LOG_LEVEL=debug  # Agregado para habilitar logs en modo debug
    ports:
      - "8080:80"
    depends_on:
      - ldap
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      # - ./phpldapadmin-config.php:/container/service/phpldapadmin/assets/config/config.php

volumes:
  ldap-data:
  ldap-config:

